# Generated by Django 4.2.7 on 2023-11-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='profiles',
            field=models.ManyToManyField(to='users.profile'),
        ),
    ]
