# Generated by Django 4.2.7 on 2023-11-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=100)),
                ('postauth', models.CharField(max_length=100)),
                ('postdes', models.TextField(max_length=400)),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
    ]
